//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLAP_Document_Upload_Test_App.Documents {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://SBA.gov/SalesforceDocumentUpload/", ConfigurationName="Documents.Documents")]
    public interface Documents {
        
        // CODEGEN: Generating message contract since the operation Store is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="Store", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DLAP_Document_Upload_Test_App.Documents.StoreResponse Store(DLAP_Document_Upload_Test_App.Documents.StoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Store", ReplyAction="*")]
        System.Threading.Tasks.Task<DLAP_Document_Upload_Test_App.Documents.StoreResponse> StoreAsync(DLAP_Document_Upload_Test_App.Documents.StoreRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://DocumentUploadDefinition.DocumentUpload")]
    public partial class DOCUMENT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dOC_IDField;
        
        private string dOC_APP_IDField;
        
        private string dOC_TYPEField;
        
        private string dOC_CONTENTSField;
        
        private string dOC_CONTENT_TYPEField;
        
        private string dOC_INSTANCE_NAMEField;
        
        private string dOC_SOURCEField;
        
        private string cREATED_BYField;
        
        private string cREATION_DATEField;
        
        private string lAST_UPDATED_BYField;
        
        private string lAST_UPDATE_DATEField;
        
        private string dOC_APPLICANT_IDField;
        
        private string dOC_AFFILIATE_IDField;
        
        private string dOC_ORIGINField;
        
        private string dOC_USR_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DOC_ID {
            get {
                return this.dOC_IDField;
            }
            set {
                this.dOC_IDField = value;
                this.RaisePropertyChanged("DOC_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DOC_APP_ID {
            get {
                return this.dOC_APP_IDField;
            }
            set {
                this.dOC_APP_IDField = value;
                this.RaisePropertyChanged("DOC_APP_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DOC_TYPE {
            get {
                return this.dOC_TYPEField;
            }
            set {
                this.dOC_TYPEField = value;
                this.RaisePropertyChanged("DOC_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DOC_CONTENTS {
            get {
                return this.dOC_CONTENTSField;
            }
            set {
                this.dOC_CONTENTSField = value;
                this.RaisePropertyChanged("DOC_CONTENTS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DOC_CONTENT_TYPE {
            get {
                return this.dOC_CONTENT_TYPEField;
            }
            set {
                this.dOC_CONTENT_TYPEField = value;
                this.RaisePropertyChanged("DOC_CONTENT_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string DOC_INSTANCE_NAME {
            get {
                return this.dOC_INSTANCE_NAMEField;
            }
            set {
                this.dOC_INSTANCE_NAMEField = value;
                this.RaisePropertyChanged("DOC_INSTANCE_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string DOC_SOURCE {
            get {
                return this.dOC_SOURCEField;
            }
            set {
                this.dOC_SOURCEField = value;
                this.RaisePropertyChanged("DOC_SOURCE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string CREATED_BY {
            get {
                return this.cREATED_BYField;
            }
            set {
                this.cREATED_BYField = value;
                this.RaisePropertyChanged("CREATED_BY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CREATION_DATE {
            get {
                return this.cREATION_DATEField;
            }
            set {
                this.cREATION_DATEField = value;
                this.RaisePropertyChanged("CREATION_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string LAST_UPDATED_BY {
            get {
                return this.lAST_UPDATED_BYField;
            }
            set {
                this.lAST_UPDATED_BYField = value;
                this.RaisePropertyChanged("LAST_UPDATED_BY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string LAST_UPDATE_DATE {
            get {
                return this.lAST_UPDATE_DATEField;
            }
            set {
                this.lAST_UPDATE_DATEField = value;
                this.RaisePropertyChanged("LAST_UPDATE_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string DOC_APPLICANT_ID {
            get {
                return this.dOC_APPLICANT_IDField;
            }
            set {
                this.dOC_APPLICANT_IDField = value;
                this.RaisePropertyChanged("DOC_APPLICANT_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string DOC_AFFILIATE_ID {
            get {
                return this.dOC_AFFILIATE_IDField;
            }
            set {
                this.dOC_AFFILIATE_IDField = value;
                this.RaisePropertyChanged("DOC_AFFILIATE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string DOC_ORIGIN {
            get {
                return this.dOC_ORIGINField;
            }
            set {
                this.dOC_ORIGINField = value;
                this.RaisePropertyChanged("DOC_ORIGIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string DOC_USR_ID {
            get {
                return this.dOC_USR_IDField;
            }
            set {
                this.dOC_USR_IDField = value;
                this.RaisePropertyChanged("DOC_USR_ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://DocumentUploadDefinition.DocumentUpload")]
    public partial class DOCUMENTRESPONSE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string statusMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string StatusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
                this.RaisePropertyChanged("StatusMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StoreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DocumentUploadDefinition.DocumentUpload", Order=0)]
        public DLAP_Document_Upload_Test_App.Documents.DOCUMENT DOCUMENT;
        
        public StoreRequest() {
        }
        
        public StoreRequest(DLAP_Document_Upload_Test_App.Documents.DOCUMENT DOCUMENT) {
            this.DOCUMENT = DOCUMENT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StoreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DocumentUploadDefinition.DocumentUpload", Order=0)]
        public DLAP_Document_Upload_Test_App.Documents.DOCUMENTRESPONSE DOCUMENTRESPONSE;
        
        public StoreResponse() {
        }
        
        public StoreResponse(DLAP_Document_Upload_Test_App.Documents.DOCUMENTRESPONSE DOCUMENTRESPONSE) {
            this.DOCUMENTRESPONSE = DOCUMENTRESPONSE;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DocumentsChannel : DLAP_Document_Upload_Test_App.Documents.Documents, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentsClient : System.ServiceModel.ClientBase<DLAP_Document_Upload_Test_App.Documents.Documents>, DLAP_Document_Upload_Test_App.Documents.Documents {
        
        public DocumentsClient() {
        }
        
        public DocumentsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DLAP_Document_Upload_Test_App.Documents.StoreResponse DLAP_Document_Upload_Test_App.Documents.Documents.Store(DLAP_Document_Upload_Test_App.Documents.StoreRequest request) {
            return base.Channel.Store(request);
        }
        
        public DLAP_Document_Upload_Test_App.Documents.DOCUMENTRESPONSE Store(DLAP_Document_Upload_Test_App.Documents.DOCUMENT DOCUMENT) {
            DLAP_Document_Upload_Test_App.Documents.StoreRequest inValue = new DLAP_Document_Upload_Test_App.Documents.StoreRequest();
            inValue.DOCUMENT = DOCUMENT;
            DLAP_Document_Upload_Test_App.Documents.StoreResponse retVal = ((DLAP_Document_Upload_Test_App.Documents.Documents)(this)).Store(inValue);
            return retVal.DOCUMENTRESPONSE;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DLAP_Document_Upload_Test_App.Documents.StoreResponse> DLAP_Document_Upload_Test_App.Documents.Documents.StoreAsync(DLAP_Document_Upload_Test_App.Documents.StoreRequest request) {
            return base.Channel.StoreAsync(request);
        }
        
        public System.Threading.Tasks.Task<DLAP_Document_Upload_Test_App.Documents.StoreResponse> StoreAsync(DLAP_Document_Upload_Test_App.Documents.DOCUMENT DOCUMENT) {
            DLAP_Document_Upload_Test_App.Documents.StoreRequest inValue = new DLAP_Document_Upload_Test_App.Documents.StoreRequest();
            inValue.DOCUMENT = DOCUMENT;
            return ((DLAP_Document_Upload_Test_App.Documents.Documents)(this)).StoreAsync(inValue);
        }
    }
}
