namespace SBA.ETRANObligation.Definition.Rules {
    using Microsoft.XLANGs.BaseTypes;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.BizTalk.Schema.Compiler", "3.0.1.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [SchemaType(SchemaTypeEnum.Document)]
    [Schema(@"http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/",@"ETranObligationTransport")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Boolean), "EnableBTAuditPayloadLog", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='EnableBTAuditPayloadLog' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"boolean")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Message.Action", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Action' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Message.AffiliateApplicationName", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='AffiliateApplicationName' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Message.AlgorithmSuite", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='AlgorithmSuite' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Message.ClientCertificate", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='ClientCertificate' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Message.CloseTimeout", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='CloseTimeout' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Message.InboundBodyLocation", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='InboundBodyLocation' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Message.InboundBodyPathExpression", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='InboundBodyPathExpression' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Message.InboundNodeEncoding", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='InboundNodeEncoding' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Message.MessageClientCredentialType", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='MessageClientCredentialType' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Message.MessageEncoding", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='MessageEncoding' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Decimal), "Message.MaxReceivedMessageSize", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='MaxReceivedMessageSize' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"integer")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Message.OpenTimeout", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='OpenTimeout' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Message.OutboundBodyLocation", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='OutboundBodyLocation' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Message.OutboundXmlTemplate", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='OutboundXmlTemplate' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Message.Password", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Password' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Boolean), "Message.PropagateFaultMessage", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='PropagateFaultMessage' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"boolean")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Message.ProxyAddress", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='ProxyAddress' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Message.ProxyToUse", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='ProxyToUse' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Message.ProxyUserName", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='ProxyUserName' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Message.SecurityMode", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='SecurityMode' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Message.SendTimeout", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='SendTimeout' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Message.ServiceCertificate", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='ServiceCertificate' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Message.TextEncoding", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='TextEncoding' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Message.TransportClientCredentialType", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='TransportClientCredentialType' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Boolean), "Message.UseAcsAuthentication", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='UseAcsAuthentication' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"boolean")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Message.UserName", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='UserName' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Boolean), "Message.UseSasAuthentication", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='UseSasAuthentication' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"boolean")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Boolean), "Message.UseSSO", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='UseSSO' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"boolean")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Port.Address", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Port' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Address' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "Port.TransportType", XPath = @"/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Port' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='TransportType' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']", XsdType = @"string")]
    [System.SerializableAttribute()]
    [SchemaRoots(new string[] {@"ETranObligationTransport"})]
    public sealed class ETranObligationTransport : Microsoft.XLANGs.BaseTypes.SchemaBase {
        
        [System.NonSerializedAttribute()]
        private static object _rawSchema;
        
        [System.NonSerializedAttribute()]
        private const string _strSchema = @"<?xml version=""1.0"" encoding=""utf-16""?>
<xs:schema xmlns=""http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/"" xmlns:b=""http://schemas.microsoft.com/BizTalk/2003"" attributeFormDefault=""unqualified"" elementFormDefault=""qualified"" targetNamespace=""http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/"" xmlns:xs=""http://www.w3.org/2001/XMLSchema"">
  <xs:element name=""ETranObligationTransport"" type=""ETranObligationTransport"">
    <xs:annotation>
      <xs:appinfo>
        <b:properties>
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='EnableBTAuditPayloadLog' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Action' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='AffiliateApplicationName' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='AlgorithmSuite' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='ClientCertificate' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='CloseTimeout' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='InboundBodyLocation' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='InboundBodyPathExpression' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='InboundNodeEncoding' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='MessageClientCredentialType' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='MessageEncoding' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='MaxReceivedMessageSize' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='OpenTimeout' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='OutboundBodyLocation' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='OutboundXmlTemplate' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Password' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='PropagateFaultMessage' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='ProxyAddress' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='ProxyToUse' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='ProxyUserName' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='SecurityMode' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='SendTimeout' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='ServiceCertificate' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='TextEncoding' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='TransportClientCredentialType' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='UseAcsAuthentication' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='UserName' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='UseSasAuthentication' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Message' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='UseSSO' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Port' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Address' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='ETranObligationTransport' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='Port' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']/*[local-name()='TransportType' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Rules/ETranObligationTransport/']"" />
        </b:properties>
      </xs:appinfo>
    </xs:annotation>
  </xs:element>
  <xs:complexType name=""ETranObligationTransport"">
    <xs:sequence>
      <xs:element minOccurs=""1"" maxOccurs=""1"" default=""false"" name=""EnableBTAuditPayloadLog"" type=""xs:boolean"" />
      <xs:element minOccurs=""1"" maxOccurs=""1"" name=""Message"" type=""Message"" />
      <xs:element minOccurs=""1"" maxOccurs=""1"" name=""Port"" type=""Port"" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name=""Message"">
    <xs:sequence>
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Action"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""AffiliateApplicationName"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" default=""Basic256"" name=""AlgorithmSuite"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""ClientCertificate"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" default=""00:01:00"" name=""CloseTimeout"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" default=""UseBodyPath"" name=""InboundBodyLocation"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" default=""/*[local-name()='Originate3Response' and namespace-uri()='']/*[local-name()='Originate3Return' and namespace-uri()='']"" name=""InboundBodyPathExpression"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" default=""String"" name=""InboundNodeEncoding"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" default=""UserName"" name=""MessageClientCredentialType"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" default=""Text"" name=""MessageEncoding"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" default=""65536"" name=""MaxReceivedMessageSize"" type=""xs:integer"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" default=""00:01:00"" name=""OpenTimeout"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" default=""UseBodyElement"" name=""OutboundBodyLocation"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" default=""&amp;lt;bts-msg-body xmlns=&quot;http://www.microsoft.com/schemas/bts2007&quot; encoding=&quot;xml&quot;/&amp;gt;"" name=""OutboundXmlTemplate"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Password"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" default=""true"" name=""PropagateFaultMessage"" type=""xs:boolean"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""ProxyAddress"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" default=""Default"" name=""ProxyToUse"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""ProxyUserName"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" default=""Transport"" name=""SecurityMode"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" default=""00:01:00"" name=""SendTimeout"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""ServiceCertificate"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" default=""utf-8"" name=""TextEncoding"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" default=""Basic"" name=""TransportClientCredentialType"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" default=""false"" name=""UseAcsAuthentication"" type=""xs:boolean"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""UserName"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" default=""false"" name=""UseSasAuthentication"" type=""xs:boolean"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" default=""false"" name=""UseSSO"" type=""xs:boolean"" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name=""Port"">
    <xs:sequence>
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Address"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" default=""WCF-BasicHttp"" name=""TransportType"" type=""xs:string"" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>";
        
        public ETranObligationTransport() {
        }
        
        public override string XmlContent {
            get {
                return _strSchema;
            }
        }
        
        public override string[] RootNodes {
            get {
                string[] _RootElements = new string [1];
                _RootElements[0] = "ETranObligationTransport";
                return _RootElements;
            }
        }
        
        protected override object RawSchema {
            get {
                return _rawSchema;
            }
            set {
                _rawSchema = value;
            }
        }
    }
}
