namespace SBA.ETRANObligation.Definition.Salesforce.Multi {
    using Microsoft.XLANGs.BaseTypes;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.BizTalk.Schema.Compiler", "3.0.1.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [SchemaType(SchemaTypeEnum.Document)]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "q", XPath = @"/*[local-name()='Request' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='q' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "ApplicationNumber", XPath = @"/*[local-name()='Request' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='ApplicationNumber' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "LoanId", XPath = @"/*[local-name()='Request' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='LoanId' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Boolean), "done", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='done' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"boolean")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.type", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='type' and namespace-uri()='']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.url", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='url' and namespace-uri()='']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Id", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Id' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.RecordType.type", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='RecordType' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='type' and namespace-uri()='']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.RecordType.url", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='RecordType' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='url' and namespace-uri()='']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.RecordType.Name", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='RecordType' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Name' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Name", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Name' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Previous_SBA_Loans__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Previous_SBA_Loans__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loan_Type__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loan_Type__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Org_Type__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Org_Type__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Application_Type__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Application_Type__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loan_Type2__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loan_Type2__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loss_Type__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loss_Type__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.FEMA_Registration_Number__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='FEMA_Registration_Number__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Boolean), "records.Loans__r.done", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='done' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"boolean")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.type", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='type' and namespace-uri()='']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.url", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='url' and namespace-uri()='']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Id", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Id' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Interest_Rate__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Interest_Rate__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Loan_Amount__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loan_Amount__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Payment_Amount__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Payment_Amount__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Secure__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Secure__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Servicing_Office__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Servicing_Office__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Total_Term__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Total_Term__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Disaster_Declaration__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Declaration__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Disaster_Declaration__r.type", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Declaration__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='type' and namespace-uri()='']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Disaster_Declaration__r.url", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Declaration__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='url' and namespace-uri()='']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Disaster_Declaration__r.Name", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Declaration__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Name' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Disaster_Declaration__r.Disaster_Damaged_Type__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Declaration__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Damaged_Type__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Disaster_Declaration__r.Physical_Number__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Declaration__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Physical_Number__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Decimal), "records.Loans__r.totalSize", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='totalSize' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"integer")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Boolean), "records.Processing_Application_Review__r.done", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Processing_Application_Review__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='done' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"boolean")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Decimal), "records.Processing_Application_Review__r.totalSize", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Processing_Application_Review__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='totalSize' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"integer")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Boolean), "records.Property__r.done", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Property__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='done' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"boolean")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Decimal), "records.Property__r.totalSize", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Property__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='totalSize' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"integer")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Boolean), "records.Applicants__r.done", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Applicants__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='done' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"boolean")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Decimal), "records.Applicants__r.totalSize", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Applicants__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='totalSize' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"integer")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Decimal), "totalSize", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='totalSize' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"integer")]
    [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Disaster_Declaration__r.EIDL_Number__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Declaration__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='EIDL_Number__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
    [System.SerializableAttribute()]
    [SchemaRoots(new string[] {@"Request", @"QueryResult"})]
    public sealed class Salesforce_Multi_Query : Microsoft.XLANGs.BaseTypes.SchemaBase {
        
        [System.NonSerializedAttribute()]
        private static object _rawSchema;
        
        [System.NonSerializedAttribute()]
        private const string _strSchema = @"<?xml version=""1.0"" encoding=""utf-16""?>
<xs:schema xmlns=""http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/"" xmlns:b=""http://schemas.microsoft.com/BizTalk/2003"" attributeFormDefault=""unqualified"" elementFormDefault=""qualified"" targetNamespace=""http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/"" xmlns:xs=""http://www.w3.org/2001/XMLSchema"">
  <xs:element name=""Request"" type=""Request"">
    <xs:annotation>
      <xs:appinfo>
        <b:properties>
          <b:property distinguished=""true"" xpath=""/*[local-name()='Request' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='q' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='Request' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='ApplicationNumber' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='Request' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='LoanId' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
        </b:properties>
      </xs:appinfo>
    </xs:annotation>
  </xs:element>
  <xs:element name=""QueryResult"" type=""QueryResult"">
    <xs:annotation>
      <xs:appinfo>
        <b:properties>
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='done' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='type' and namespace-uri()='']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='url' and namespace-uri()='']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Id' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='RecordType' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='type' and namespace-uri()='']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='RecordType' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='url' and namespace-uri()='']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='RecordType' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Name' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Name' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Previous_SBA_Loans__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loan_Type__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Org_Type__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Application_Type__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loan_Type2__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loss_Type__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='FEMA_Registration_Number__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='done' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='type' and namespace-uri()='']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='url' and namespace-uri()='']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Id' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Interest_Rate__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loan_Amount__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Payment_Amount__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Secure__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Servicing_Office__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Total_Term__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Declaration__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Declaration__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='type' and namespace-uri()='']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Declaration__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='url' and namespace-uri()='']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Declaration__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Name' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Declaration__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Damaged_Type__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Declaration__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Physical_Number__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='totalSize' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Processing_Application_Review__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='done' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Processing_Application_Review__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='totalSize' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Property__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='done' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Property__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='totalSize' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Applicants__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='done' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Applicants__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='totalSize' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='totalSize' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
          <b:property distinguished=""true"" xpath=""/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Declaration__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='EIDL_Number__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']"" />
        </b:properties>
      </xs:appinfo>
    </xs:annotation>
  </xs:element>
  <xs:complexType name=""Request"">
    <xs:sequence>
      <xs:element minOccurs=""1"" maxOccurs=""1"" default=""SELECT Id, RecordType.Name, Name, Previous_SBA_Loans__c, Loan_Type__c, Org_Type__c, Application_Type__c, Loan_Type2__c, Loss_Type__c, FEMA_Registration_Number__c, (SELECT Id, Interest_Rate__c, Loan_Amount__c, Payment_Amount__c, Secure__c, Servicing_Office__c, Total_Term__c, Disaster_Declaration__c, Disaster_Declaration__r.Name, Disaster_Declaration__r.Disaster_Damaged_Type__c, Disaster_Declaration__r.Physical_Number__c, Disaster_Declaration__r.EIDL_Number__c FROM Loans__r WHERE Id=@LoanId), (SELECT Credit_Elsewhere_Test__c, Physical_Allocated_Amount__c, EIDL_Allocated_Amount__c FROM Processing_Application_Review__r), (SELECT Id, Property_Address__c, City__c, State__c, Zip_Code__c FROM Property__r WHERE Active__c=true), (SELECT Id, RecordType.Name, Name, Primary_Applicant__c, Tax_ID__c, Related_Parent__r.Tax_ID__c, Entity_Type__c, Applicant_Relation_Type__c, Ownership_Percent__c, Borrower_Guarantor__c, Account__r.Id, Account__r.Name, Account__r.Business_Type__c, Account__r.Trade_Name__c, Account__r.Phone, Account__r.Phone_Number__c, Account__r.ShippingStreet, Account__r.ShippingCity, Account__r.ShippingState, Account__r.ShippingPostalCode, Contact__r.Id, Contact__r.Birthdate, Contact__r.Title, Contact__r.FirstName, Contact__r.LastName, Contact__r.MiddleName, Contact__r.Suffix, Contact__r.Phone, Contact__r.MobilePhone, Contact__r.Work_Phone__c, Contact__r.MailingStreet, Contact__r.MailingCity, Contact__r.MailingState, Contact__r.MailingPostalCode FROM Applicants__r WHERE Active__c=true) FROM Application__c WHERE Name=@ApplicationNumber"" name=""q"" type=""xs:string"" />
      <xs:element minOccurs=""1"" maxOccurs=""1"" name=""ApplicationNumber"" type=""xs:string"" />
      <xs:element minOccurs=""1"" maxOccurs=""1"" name=""LoanId"" type=""xs:string"" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name=""QueryResult"">
    <xs:sequence>
      <xs:element minOccurs=""1"" maxOccurs=""1"" default=""false"" name=""done"" type=""xs:boolean"" />
      <xs:element minOccurs=""1"" maxOccurs=""1"" name=""records"" type=""Application__c"" />
      <xs:element minOccurs=""1"" maxOccurs=""1"" default=""0"" name=""totalSize"" type=""xs:integer"" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name=""Application__c"">
    <xs:sequence>
      <xs:element minOccurs=""1"" maxOccurs=""1"" name=""Id"" type=""xs:string"" />
      <xs:element minOccurs=""1"" maxOccurs=""1"" name=""RecordType"" type=""RecordType"" />
      <xs:element minOccurs=""1"" maxOccurs=""1"" name=""Name"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Previous_SBA_Loans__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Loan_Type__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Org_Type__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Application_Type__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Loan_Type2__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Loss_Type__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""FEMA_Registration_Number__c"" type=""xs:string"" />
      <xs:element minOccurs=""1"" maxOccurs=""1"" name=""Loans__r"" type=""Loans__r"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Processing_Application_Review__r"" type=""Processing_Application_Review__r"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Property__r"" type=""Property__r"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Applicants__r"" type=""Applicants__r"" />
    </xs:sequence>
    <xs:attribute default=""Application__c"" name=""type"" type=""xs:string"" />
    <xs:attribute name=""url"" type=""xs:string"" />
  </xs:complexType>
  <xs:complexType name=""RecordType"">
    <xs:sequence>
      <xs:element minOccurs=""1"" maxOccurs=""1"" name=""Name"" type=""xs:string"" />
    </xs:sequence>
    <xs:attribute default=""RecordType"" name=""type"" type=""xs:string"" />
    <xs:attribute name=""url"" type=""xs:string"" />
  </xs:complexType>
  <xs:complexType name=""Loans__r"">
    <xs:sequence>
      <xs:element minOccurs=""1"" maxOccurs=""1"" default=""false"" name=""done"" type=""xs:boolean"" />
      <xs:element minOccurs=""1"" maxOccurs=""1"" name=""records"" type=""Loan__c"" />
      <xs:element minOccurs=""1"" maxOccurs=""1"" default=""0"" name=""totalSize"" type=""xs:integer"" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name=""Loan__c"">
    <xs:sequence>
      <xs:element minOccurs=""1"" maxOccurs=""1"" name=""Id"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Interest_Rate__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Loan_Amount__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Payment_Amount__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Secure__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Servicing_Office__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Total_Term__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Disaster_Declaration__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Disaster_Declaration__r"" type=""Disaster__c"" />
    </xs:sequence>
    <xs:attribute default=""Loan__c"" name=""type"" type=""xs:string"" />
    <xs:attribute name=""url"" type=""xs:string"" />
  </xs:complexType>
  <xs:complexType name=""Disaster__c"">
    <xs:sequence>
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Name"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Disaster_Damaged_Type__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Physical_Number__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""EIDL_Number__c"" type=""xs:string"" />
    </xs:sequence>
    <xs:attribute default=""Disaster__c"" name=""type"" type=""xs:string"" />
    <xs:attribute name=""url"" type=""xs:string"" />
  </xs:complexType>
  <xs:complexType name=""Processing_Application_Review__r"">
    <xs:sequence>
      <xs:element minOccurs=""1"" maxOccurs=""1"" default=""false"" name=""done"" type=""xs:boolean"" />
      <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""records"" type=""Processing_Application_Review__c"" />
      <xs:element minOccurs=""1"" maxOccurs=""1"" default=""0"" name=""totalSize"" type=""xs:integer"" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name=""Processing_Application_Review__c"">
    <xs:sequence>
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Credit_Elsewhere_Test__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Physical_Allocated_Amount__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""EIDL_Allocated_Amount__c"" type=""xs:string"" />
    </xs:sequence>
    <xs:attribute default=""Processing_Application_Review__c"" name=""type"" type=""xs:string"" />
    <xs:attribute name=""url"" type=""xs:string"" />
  </xs:complexType>
  <xs:complexType name=""Property__r"">
    <xs:sequence>
      <xs:element minOccurs=""1"" maxOccurs=""1"" default=""false"" name=""done"" type=""xs:boolean"" />
      <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""records"" type=""Property__c"" />
      <xs:element minOccurs=""1"" maxOccurs=""1"" default=""0"" name=""totalSize"" type=""xs:integer"" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name=""Property__c"">
    <xs:sequence>
      <xs:element minOccurs=""1"" maxOccurs=""1"" name=""Id"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Property_Address__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""City__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""State__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Zip_Code__c"" type=""xs:string"" />
    </xs:sequence>
    <xs:attribute default=""Property__c"" name=""type"" type=""xs:string"" />
    <xs:attribute name=""url"" type=""xs:string"" />
  </xs:complexType>
  <xs:complexType name=""Applicants__r"">
    <xs:sequence>
      <xs:element minOccurs=""1"" maxOccurs=""1"" default=""false"" name=""done"" type=""xs:boolean"" />
      <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""records"" type=""Applicant__c"" />
      <xs:element minOccurs=""1"" maxOccurs=""1"" default=""0"" name=""totalSize"" type=""xs:integer"" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name=""Applicant__c"">
    <xs:sequence>
      <xs:element minOccurs=""1"" maxOccurs=""1"" name=""Id"" type=""xs:string"" />
      <xs:element minOccurs=""1"" maxOccurs=""1"" name=""RecordType"">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs=""1"" maxOccurs=""1"" name=""Name"" type=""xs:string"" />
          </xs:sequence>
          <xs:attribute default=""RecordType"" name=""type"" type=""xs:string"" />
          <xs:attribute name=""url"" type=""xs:string"" />
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs=""1"" maxOccurs=""1"" name=""Name"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Primary_Applicant__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Tax_ID__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Related_Parent__r"" type=""Related_Parent__r"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Entity_Type__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Applicant_Relation_Type__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Ownership_Percent__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Borrower_Guarantor__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Account__r"" type=""Account"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Contact__r"" type=""Contact"" />
    </xs:sequence>
    <xs:attribute default=""Applicant__c"" name=""type"" type=""xs:string"" />
    <xs:attribute name=""url"" type=""xs:string"" />
  </xs:complexType>
  <xs:complexType name=""Related_Parent__r"">
    <xs:sequence>
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Tax_ID__c"" type=""xs:string"" />
    </xs:sequence>
    <xs:attribute default=""Applicant__c"" name=""type"" type=""xs:string"" />
    <xs:attribute name=""url"" type=""xs:string"" />
  </xs:complexType>
  <xs:complexType name=""Account"">
    <xs:sequence>
      <xs:element minOccurs=""1"" maxOccurs=""1"" name=""Id"" type=""xs:string"" />
      <xs:element minOccurs=""1"" maxOccurs=""1"" name=""Name"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Business_Type__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Trade_Name__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Phone"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Phone_Number__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""ShippingStreet"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""ShippingCity"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""ShippingState"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""ShippingPostalCode"" type=""xs:string"" />
    </xs:sequence>
    <xs:attribute default=""Account"" name=""type"" type=""xs:string"" />
    <xs:attribute name=""url"" type=""xs:string"" />
  </xs:complexType>
  <xs:complexType name=""Contact"">
    <xs:sequence>
      <xs:element minOccurs=""1"" maxOccurs=""1"" name=""Id"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Birthdate"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Title"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""FirstName"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""LastName"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""MiddleName"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Suffix"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Phone"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""MobilePhone"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""Work_Phone__c"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""MailingStreet"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""MailingCity"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""MailingState"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""1"" name=""MailingPostalCode"" type=""xs:string"" />
    </xs:sequence>
    <xs:attribute default=""Contact"" name=""type"" type=""xs:string"" />
    <xs:attribute name=""url"" type=""xs:string"" />
  </xs:complexType>
</xs:schema>";
        
        public Salesforce_Multi_Query() {
        }
        
        public override string XmlContent {
            get {
                return _strSchema;
            }
        }
        
        public override string[] RootNodes {
            get {
                string[] _RootElements = new string [2];
                _RootElements[0] = "Request";
                _RootElements[1] = "QueryResult";
                return _RootElements;
            }
        }
        
        protected override object RawSchema {
            get {
                return _rawSchema;
            }
            set {
                _rawSchema = value;
            }
        }
        
        [Schema(@"http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/",@"Request")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "q", XPath = @"/*[local-name()='Request' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='q' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "ApplicationNumber", XPath = @"/*[local-name()='Request' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='ApplicationNumber' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "LoanId", XPath = @"/*[local-name()='Request' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='LoanId' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"Request"})]
        public sealed class Request : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public Request() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "Request";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/",@"QueryResult")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Boolean), "done", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='done' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"boolean")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.type", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='type' and namespace-uri()='']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.url", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='url' and namespace-uri()='']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Id", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Id' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.RecordType.type", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='RecordType' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='type' and namespace-uri()='']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.RecordType.url", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='RecordType' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='url' and namespace-uri()='']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.RecordType.Name", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='RecordType' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Name' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Name", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Name' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Previous_SBA_Loans__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Previous_SBA_Loans__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loan_Type__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loan_Type__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Org_Type__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Org_Type__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Application_Type__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Application_Type__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loan_Type2__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loan_Type2__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loss_Type__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loss_Type__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.FEMA_Registration_Number__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='FEMA_Registration_Number__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Boolean), "records.Loans__r.done", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='done' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"boolean")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.type", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='type' and namespace-uri()='']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.url", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='url' and namespace-uri()='']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Id", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Id' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Interest_Rate__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Interest_Rate__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Loan_Amount__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loan_Amount__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Payment_Amount__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Payment_Amount__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Secure__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Secure__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Servicing_Office__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Servicing_Office__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Total_Term__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Total_Term__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Disaster_Declaration__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Declaration__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Disaster_Declaration__r.type", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Declaration__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='type' and namespace-uri()='']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Disaster_Declaration__r.url", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Declaration__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/@*[local-name()='url' and namespace-uri()='']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Disaster_Declaration__r.Name", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Declaration__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Name' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Disaster_Declaration__r.Disaster_Damaged_Type__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Declaration__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Damaged_Type__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Disaster_Declaration__r.Physical_Number__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Declaration__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Physical_Number__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Decimal), "records.Loans__r.totalSize", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='totalSize' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"integer")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Boolean), "records.Processing_Application_Review__r.done", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Processing_Application_Review__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='done' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"boolean")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Decimal), "records.Processing_Application_Review__r.totalSize", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Processing_Application_Review__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='totalSize' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"integer")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Boolean), "records.Property__r.done", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Property__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='done' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"boolean")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Decimal), "records.Property__r.totalSize", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Property__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='totalSize' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"integer")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Boolean), "records.Applicants__r.done", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Applicants__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='done' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"boolean")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Decimal), "records.Applicants__r.totalSize", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Applicants__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='totalSize' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"integer")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.Decimal), "totalSize", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='totalSize' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"integer")]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute(typeof(System.String), "records.Loans__r.records.Disaster_Declaration__r.EIDL_Number__c", XPath = @"/*[local-name()='QueryResult' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Loans__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='records' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='Disaster_Declaration__r' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']/*[local-name()='EIDL_Number__c' and namespace-uri()='http://SBA.gov/ETRANObligation/Definition/Salesforce/Multi/Query/']", XsdType = @"string")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"QueryResult"})]
        public sealed class QueryResult : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public QueryResult() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "QueryResult";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
    }
}
